-- Seed sector taxonomy (mirrors common SA job-board categories)

insert into sectors (name, slug) values
  ('Academic', 'academic'),
  ('Accounting', 'accounting'),
  ('Admin', 'admin'),
  ('Advertising', 'advertising'),
  ('Agriculture', 'agriculture'),
  ('Automotive', 'automotive'),
  ('Aviation', 'aviation'),
  ('Banking', 'banking'),
  ('Business Management', 'business-management'),
  ('Call Centre', 'call-centre'),
  ('Chemical', 'chemical'),
  ('Construction', 'construction'),
  ('Consulting', 'consulting'),
  ('Design Services', 'design-services'),
  ('Education', 'education'),
  ('Engineering', 'engineering'),
  ('Entertainment', 'entertainment'),
  ('Finance', 'finance'),
  ('FMCG', 'fmcg'),
  ('Freight', 'freight'),
  ('General', 'general'),
  ('Government & Parastatals', 'government-parastatals'),
  ('Health & Safety', 'health-safety'),
  ('Health, Fitness & Beauty', 'health-fitness-beauty'),
  ('Hospitality', 'hospitality'),
  ('Human Resources', 'human-resources'),
  ('Import & Export', 'import-export'),
  ('Insurance', 'insurance'),
  ('Investment', 'investment'),
  ('IT', 'it'),
  ('Legal', 'legal'),
  ('Logistics', 'logistics'),
  ('Management', 'management'),
  ('Manufacturing', 'manufacturing'),
  ('Marketing', 'marketing'),
  ('Medical', 'medical'),
  ('Mining', 'mining'),
  ('Motoring', 'motoring'),
  ('Pharmaceutical', 'pharmaceutical'),
  ('Procurement', 'procurement'),
  ('Property', 'property'),
  ('Real Estate', 'real-estate'),
  ('Recruitment', 'recruitment'),
  ('Retail', 'retail'),
  ('Sales', 'sales'),
  ('Security', 'security'),
  ('Technical', 'technical'),
  ('Technology', 'technology'),
  ('Telecommunications', 'telecommunications'),
  ('Trades & Services', 'trades-services'),
  ('Travel & Tourism', 'travel-tourism'),
  ('Warehousing', 'warehousing')
on conflict (slug) do nothing;
